version: '3'
services:
  quarkus_app:
    image: quarkus/application
    networks:
      - quarkus_network
    ports:
      - "9882:9882"
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - quarkus_network
    ports:
      - "27017:27017"

networks:
  quarkus_network:
    driver: bridge
